apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
  labels:
    app: kavvotingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: kavvotingapp
  template:
    metatdata:
      name: voting-app-pod
      labels:
        name: voting-app
        app: kavvotingapp
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80