apiVersion: v1
kind: Service
metatadata:
  name: db
  labels:
    name: db-service
    app: kavvotingapp
spec:
  ports:
    - port: 5432
      tagertPort: 5432
  selector:
       name: postgres-pod
       app: kavvotingapp