apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavapp-deployment
  labels:
    app: kavapp
    type: front-end

spec:
  template:
    metadata:
      name: kavapp-pod
      labels:
        app: kavapp
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 2
  selector:
    matchLabels:
      app: front-end