apiVersion: v1
kind: ReplicationController
metadata:
  name: kavapp-replica
  labels:
    app: kavapp
    type: front-end
spec:
   template:
      metadata:
        name: kavapp-pod
        labels:
          app: kavapp
          type: front-end
      spec:
        containners:
          - name: nginx-container
            image: nginx

   replicas: 3