apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kavapp-replicaset
  labels:
    app: kavapp
    type: front-end
spec:
  template:
    metadata:
      name: kavapp-pod
      labels:
        app: kavapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      type: front-end